-- Triforce Pieces
ConditionalConsumable("Triforce Pieces", "triforce_pieces", "images/equipment/triforce_piece.png")

-- Coins
ConditionalConsumable("Red Coins", "red_coins", "images/coins/red_coin.png")
ConditionalConsumable("Yellow Coins", "yellow_coins", "images/coins/yellow_coin.png")
ConditionalConsumable("Green Coins", "green_coins", "images/coins/green_coin.png")
ConditionalConsumable("Blue Coins", "blue_coins", "images/coins/blue_coin.png")

-- Songs
CheckableToggle("Zelda's Lullaby", "zeldas_lullaby", "images/songs/zeldas_lullaby.png", true)
CheckableToggle("Epona's Song", "eponas_song", "images/songs/eponas_song.png", true)
CheckableToggle("Saria's Song", "sarias_song", "images/songs/sarias_song.png", true)
CheckableToggle("Sun's Song", "suns_song", "images/songs/suns_song.png", true)
CheckableToggle("Scarecrow Song (OoT)", "scarecrow_song_oot", "images/songs/scarecrow_song_oot.png", true)
CheckableToggle("Song of Time", "song_of_time", "images/songs/song_of_time.png", true)
CheckableToggle("Song of Healing", "song_of_healing", "images/songs/song_of_healing.png", true)
CheckableToggle("Song of Soaring", "song_of_soaring", "images/songs/song_of_soaring.png", true)
CheckableToggle("Song of Storms", "song_of_storms", "images/songs/song_of_storms.png", true)
CheckableToggle("Scarecrow Song (MM)", "scarecrow_song_mm", "images/songs/scarecrow_song_mm.png", true)
CheckableToggle("Minuet of Forest", "minuet_of_forest", "images/songs/minuet_of_forest.png", true)
CheckableToggle("Bolero of Fire", "bolero_of_fire", "images/songs/bolero_of_fire.png", true)
CheckableToggle("Serenade of Water", "serenade_of_water", "images/songs/serenade_of_water.png", true)
CheckableToggle("Requiem of Spirit", "requiem_of_spirit", "images/songs/requiem_of_spirit.png", true)
CheckableToggle("Nocturne of Shadow", "nocturne_of_shadow", "images/songs/nocturne_of_shadow.png", true)
CheckableToggle("Prelude of Light", "prelude_of_light", "images/songs/prelude_of_light.png", true)
CheckableToggle("Sonata of Awakening", "sonata_of_awakening", "images/songs/sonata_of_awakening.png", true)
CheckableProgressive("Goron Lullaby", "goron_lullaby", { {"images/songs/goron_lullaby.png", "@disabled"}, {"images/songs/lullaby_intro.png"}, {"images/songs/goron_lullaby.png"} }, true)
CheckableToggle("New Wave Bossa Nova", "new_wave_bossa_nova", "images/songs/new_wave_bossa_nova.png", true)
CheckableToggle("Elegy of Emptiness", "elegy_of_emptiness", "images/songs/elegy_of_emptiness.png", true)
CheckableToggle("Oath to Order", "oath_to_order", "images/songs/oath_to_order.png", true)

-- Owl Statues
ProgressiveVariableImage("Clock Town Owl Statue", "owl_clock_town", false, { {"images/owls/clock_town.png", "@disabled"}, {"images/owls/clock_town.png"} }, { {"images/owls/blank.png"} })
ProgressiveVariableImage("Milk Road Owl Statue", "owl_milk_road", false, { {"images/owls/milk_road.png", "@disabled"}, {"images/owls/milk_road.png"} }, { {"images/owls/blank.png"} })
ProgressiveVariableImage("Southern Swamp Owl Statue", "owl_southern_swamp", false, { {"images/owls/southern_swamp.png", "@disabled"}, {"images/owls/southern_swamp.png"} }, { {"images/owls/blank.png"} })
ProgressiveVariableImage("Woodfall Owl Statue", "owl_woodfall", false, { {"images/owls/woodfall.png", "@disabled"}, {"images/owls/woodfall.png"} }, { {"images/owls/blank.png"} })
ProgressiveVariableImage("Mountain Village Owl Statue", "owl_mountain_village", false, { {"images/owls/mountain_village.png", "@disabled"}, {"images/owls/mountain_village.png"} }, { {"images/owls/blank.png"} })
ProgressiveVariableImage("Snowhead Owl Statue", "owl_snowhead", false, { {"images/owls/snowhead.png", "@disabled"}, {"images/owls/snowhead.png"} }, { {"images/owls/blank.png"} })
ProgressiveVariableImage("Great Bay Coast Owl Statue", "owl_great_bay_coast", false, { {"images/owls/great_bay_coast.png", "@disabled"}, {"images/owls/great_bay_coast.png"} }, { {"images/owls/blank.png"} })
ProgressiveVariableImage("Zora Cape Owl Statue", "owl_zora_cape", false, { {"images/owls/zora_cape.png", "@disabled"}, {"images/owls/zora_cape.png"} }, { {"images/owls/blank.png"} })
ProgressiveVariableImage("Ikana Canyon Owl Statue", "owl_ikana_canyon", false, { {"images/owls/ikana_canyon.png", "@disabled"}, {"images/owls/ikana_canyon.png"} }, { {"images/owls/blank.png"} })
ProgressiveVariableImage("Stone Tower Owl Statue", "owl_stone_tower", false, { {"images/owls/stone_tower.png", "@disabled"}, {"images/owls/stone_tower.png"} }, { {"images/owls/blank.png"} })

-- Clocks
ConditionalToggle("1st Day Clock", "1st_day_clock", false, "images/clocks/1st_day.png")
ConditionalToggle("1st Night Clock", "1st_night_clock", false, "images/clocks/1st_night.png")
ConditionalToggle("2nd Day Clock", "2nd_day_clock", false, "images/clocks/2nd_day.png")
ConditionalToggle("2nd Night Clock", "2nd_night_clock", false, "images/clocks/2nd_night.png")
ConditionalToggle("3rd Day Clock", "3rd_day_clock", false, "images/clocks/3rd_day.png")
ConditionalToggle("3rd Night Clock", "3rd_night_clock", false, "images/clocks/3rd_night.png")

-- Equipment & Items
ProgressiveVariableImage("Hylian/Hero's Shield", "hylian_heros_shield", false, { {"images/equipment/hylian_shield.png", "@disabled"}, {"images/equipment/hylian_shield.png"} }, { {"images/equipment/heros_shield.png", "@disabled"}, {"images/equipment/heros_shield.png"} })
ProgressiveVariableImage("Mirror Shield", "mirror_shield", false, { {"images/equipment/mirror_shield_oot.png", "@disabled"}, {"images/equipment/mirror_shield_oot.png"} }, { {"images/equipment/mirror_shield_mm.png", "@disabled"}, {"images/equipment/mirror_shield_mm.png"} })
ProgressiveVariableImage("Kokiri Sword", "kokiri_sword", false, { {"images/equipment/kokiri_sword_oot.png", "@disabled"}, {"images/equipment/kokiri_sword_oot.png"}, {"images/equipment/razor_sword.png"}, {"images/equipment/gilded_sword.png"} }, { {"images/equipment/kokiri_sword_mm.png", "@disabled"}, {"images/equipment/kokiri_sword_mm.png"}, {"images/equipment/razor_sword.png"}, {"images/equipment/gilded_sword.png"} })
ProgressiveVariableImage("Fairy/Hero's Bow", "fairy_heros_bow", false, { {"images/items/fairy_bow.png", "@disabled"}, {"images/items/fairy_bow.png"}, {"images/items/fairy_bow.png"}, {"images/items/fairy_bow.png"} }, { {"images/items/heros_bow.png", "@disabled"}, {"images/items/heros_bow.png"}, {"images/items/heros_bow.png"}, {"images/items/heros_bow.png"} })
ProgressiveVariableImage("Hookshot", "hookshot", false, { {"images/items/short_hookshot.png", "@disabled"}, {"images/items/short_hookshot.png"}, {"images/items/longshot.png"} }, { {"images/items/short_hookshot.png", "@disabled"}, {"images/items/short_hookshot.png"}, {"images/items/mm_hookshot.png"} })

ConditionalConsumable("Eggs", "eggs", "images/sidequests/egg.png")
ConditionalToggle("Chicken", "chicken", false, "images/sidequests/cucco.png")
ConditionalToggle("Zelda's Letter", "zeldas_letter", false, "images/sidequests/zeldas_letter.png")

local wallet = ProgressiveVariableImage("Wallet", "wallet", false, { {"images/equipment/wallet1.png", "@disabled"}, {"images/equipment/wallet1.png"}, {"images/equipment/wallet1.png"}, {"images/equipment/wallet2.png"}, {"images/equipment/wallet2.png"}, {"images/equipment/wallet2.png"} }, { {nil} })
wallet:setStage(1)

ConditionalConsumable("Gold Skulltula Tokens", "gold_skulltula_tokens", "images/sidequests/gold_skulltula_token.png")
ConditionalConsumable("Swamp Skulltula Tokens", "swamp_skulltula_tokens", "images/sidequests/swamp_skulltula_token.png")
ConditionalConsumable("Ocean Skulltula Tokens", "ocean_skulltula_tokens", "images/sidequests/ocean_skulltula_token.png")

ConditionalToggle("Clock Town Map", "tingle_map_clock_town", false, "images/equipment/maps/clock_town.png")
ConditionalToggle("Romani Ranch Map", "tingle_map_romani_ranch", false, "images/equipment/maps/romani_ranch.png")
ConditionalToggle("Woodfall Map", "tingle_map_woodfall", false, "images/equipment/maps/woodfall.png")
ConditionalToggle("Snowhead Map", "tingle_map_snowhead", false, "images/equipment/maps/snowhead.png")
ConditionalToggle("Great Bay Map", "tingle_map_great_bay", false, "images/equipment/maps/great_bay.png")
ConditionalToggle("Stone Tower Map", "tingle_map_stone_tower", false, "images/equipment/maps/stone_tower.png")

-- Trade Quests
CheckableToggle("Pocket Cucco", "pocket_cucco", "images/sidequests/cucco.png", false)
CheckableToggle("Cojiro", "cojiro", "images/sidequests/cojiro.png", false)
CheckableToggle("Odd Mushroom", "odd_mushroom", "images/sidequests/odd_mushroom.png", false)
CheckableToggle("Odd Potion", "odd_potion", "images/sidequests/odd_potion.png", false)
CheckableToggle("Poacher's Saw", "poachers_saw", "images/sidequests/poachers_saw.png", false)
CheckableToggle("Broken Goron Sword", "broken_goron_sword", "images/sidequests/broken_goron_sword.png", false)
CheckableToggle("Prescription", "prescription", "images/sidequests/prescription.png", false)
CheckableToggle("Eyeball Frog", "eyeball_frog", "images/sidequests/eyeball_frog.png", false)
CheckableToggle("Eye Drops", "eye_drops", "images/sidequests/eye_drops.png", false)
CheckableToggle("Claim Check", "claim_check", "images/sidequests/claim_check.png", false)
CheckableToggle("Moon's Tear", "moons_tear", "images/sidequests/moons_tear.png", false)
CheckableToggle("Land Title Deed", "land_title_deed", "images/sidequests/land_title_deed.png", false)
CheckableToggle("Swamp Title Deed", "swamp_title_deed", "images/sidequests/swamp_title_deed.png", false)
CheckableToggle("Mountain Title Deed", "mountain_title_deed", "images/sidequests/mountain_title_deed.png", false)
CheckableToggle("Ocean Title Deed", "ocean_title_deed", "images/sidequests/ocean_title_deed.png", false)
CheckableToggle("Room Key", "room_key", "images/sidequests/room_key.png", false)
CheckableToggle("Letter to Kafei", "letter_to_kafei", "images/sidequests/letter_to_kafei.png", false)
CheckableToggle("Pendant of Memories", "pendant_of_memories", "images/sidequests/pendant_of_memories.png", false)
CheckableToggle("Special Delivery to Mama", "special_delivery_to_mama", "images/sidequests/special_delivery_to_mama.png", false)

-- Dungeons & Town Fairy
ProgressiveVariableImage("Clock Town Label", "clock_town_label", false, { {"images/dungeons/labels/clock_town.png"} }, { {nil} })
ConditionalToggle("Clock Town Stray Fairy", "clock_town_stray_fairy", false, "images/dungeons/clocktown_fairy.png")

ConditionalToggle("Skeleton Key", "skeleton_key", false, "images/dungeons/skeleton_key.png")
ConditionalToggle("Magical Rupee", "magical_rupee", false, "images/dungeons/magical_rupee.png")

ProgressiveVariableImage("Woodfall Temple Map", "woodfall_temple_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Woodfall Temple Compass", "woodfall_temple_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Woodfall Temple Small Keys", "woodfall_temple_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Woodfall Temple Boss Key", "woodfall_temple_boss_key", false, "images/dungeons/boss_key.png")
ConditionalConsumable("Woodfall Temple Stray Fairies", "woodfall_temple_stray_fairies", "images/dungeons/woodfall_fairy.png")

ProgressiveVariableImage("Snowhead Temple Map", "snowhead_temple_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Snowhead Temple Compass", "snowhead_temple_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Snowhead Temple Small Keys", "snowhead_temple_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Snowhead Temple Boss Key", "snowhead_temple_boss_key", false, "images/dungeons/boss_key.png")
ConditionalConsumable("Snowhead Temple Stray Fairies", "snowhead_temple_stray_fairies", "images/dungeons/snowhead_fairy.png")

ProgressiveVariableImage("Great Bay Temple Map", "great_bay_temple_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Great Bay Temple Compass", "great_bay_temple_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Great Bay Temple Small Keys", "great_bay_temple_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Great Bay Temple Boss Key", "great_bay_temple_boss_key", false, "images/dungeons/boss_key.png")
ConditionalConsumable("Great Bay Temple Stray Fairies", "great_bay_temple_stray_fairies", "images/dungeons/greatbay_fairy.png")

ProgressiveVariableImage("Stone Tower Temple Map", "stone_tower_temple_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Stone Tower Temple Compass", "stone_tower_temple_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Stone Tower Temple Small Keys", "stone_tower_temple_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Stone Tower Temple Boss Key", "stone_tower_temple_boss_key", false, "images/dungeons/boss_key.png")
ConditionalConsumable("Stone Tower Temple Stray Fairies", "stone_tower_temple_stray_fairies", "images/dungeons/stonetower_fairy.png")

ProgressiveVariableImage("Thieves' Hideout Label", "thieves_hideout_label", false, { {"images/dungeons/labels/thieves_hideout.png"} }, { {nil} })
ConditionalConsumable("Thieves' Hideout Small Keys", "thieves_hideout_small_keys", "images/dungeons/small_key.png")

ProgressiveVariableImage("Treasure Chest Game Label", "treasure_chest_game_label", false, { {"images/dungeons/labels/treasure_chest_game.png"} }, { {nil} })
ConditionalConsumable("Treasure Chest Game Small Keys", "treasure_chest_game_small_keys", "images/dungeons/small_key.png")

ProgressiveVariableImage("Deku Tree Map", "deku_tree_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Deku Tree Compass", "deku_tree_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })

ProgressiveVariableImage("Dodongo's Cavern Map", "dodongos_cavern_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Dodongo's Cavern Compass", "dodongos_cavern_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Dodongo's Cavern Silver Rupees", "dodongos_cavern_sr", "images/dungeons/silver_rupee.png")

ProgressiveVariableImage("Jabu-Jabu Map", "jabu-jabu_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Jabu-Jabu Compass", "jabu-jabu_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })

ProgressiveVariableImage("Forest Temple Map", "forest_temple_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Forest Temple Compass", "forest_temple_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Forest Temple Small Keys", "forest_temple_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Forest Temple Boss Key", "forest_temple_boss_key", false, "images/dungeons/boss_key.png")

ProgressiveVariableImage("Fire Temple Map", "fire_temple_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Fire Temple Compass", "fire_temple_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Fire Temple Small Keys", "fire_temple_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Fire Temple Boss Key", "fire_temple_boss_key", false, "images/dungeons/boss_key.png")

ProgressiveVariableImage("Water Temple Map", "water_temple_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Water Temple Compass", "water_temple_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Water Temple Small Keys", "water_temple_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Water Temple Boss Key", "water_temple_boss_key", false, "images/dungeons/boss_key.png")

ProgressiveVariableImage("Spirit Temple Map", "spirit_temple_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Spirit Temple Compass", "spirit_temple_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Spirit Temple Silver Rupees (Child)", "spirit_temple_sr_child", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Spirit Temple Silver Rupees (Sun)", "spirit_temple_sr_sun", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Spirit Temple Silver Rupees (Boulders)", "spirit_temple_sr_boulders", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Spirit Temple Silver Rupees (Lobby)", "spirit_temple_sr_lobby", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Spirit Temple Silver Rupees (Adult)", "spirit_temple_sr_adult", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Spirit Temple Small Keys", "spirit_temple_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Spirit Temple Boss Key", "spirit_temple_boss_key", false, "images/dungeons/boss_key.png")

ProgressiveVariableImage("Shadow Temple Map", "shadow_temple_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Shadow Temple Compass", "shadow_temple_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Shadow Temple Silver Rupees (Scythe)", "shadow_temple_sr_scythe", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Shadow Temple Silver Rupees (Pit)", "shadow_temple_sr_pit", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Shadow Temple Silver Rupees (Spikes)", "shadow_temple_sr_spikes", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Shadow Temple Silver Rupees (Blades)", "shadow_temple_sr_blades", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Shadow Temple Small Keys", "shadow_temple_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Shadow Temple Boss Key", "shadow_temple_boss_key", false, "images/dungeons/boss_key.png")

ProgressiveVariableImage("Ice Cavern Label", "ice_cavern_label", true, { {"images/dungeons/labels/ice_cavern.png"}, {"images/dungeons/labels/ice_cavern.png", "overlay|images/overlays/va.png"}, {"images/dungeons/labels/ice_cavern.png", "overlay|images/overlays/mq.png"} }, { {nil} })
ProgressiveVariableImage("Ice Cavern Map", "ice_cavern_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Ice Cavern Compass", "ice_cavern_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Ice Cavern Silver Rupees (Scythe)", "ice_cavern_sr_scythe", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Ice Cavern Silver Rupees (Block)", "ice_cavern_sr_block", "images/dungeons/silver_rupee.png")

ProgressiveVariableImage("Bottom of the Well Label", "bottom_of_the_well_label", true, { {"images/dungeons/labels/bottom_of_the_well.png"}, {"images/dungeons/labels/bottom_of_the_well.png", "overlay|images/overlays/va.png"}, {"images/dungeons/labels/bottom_of_the_well.png", "overlay|images/overlays/mq.png"} }, { {nil} })
ProgressiveVariableImage("Bottom of the Well Map", "bottom_of_the_well_map", false, { {"images/dungeons/map.png", "@disabled"}, {"images/dungeons/map.png"} }, { {nil} })
ProgressiveVariableImage("Bottom of the Well Compass", "bottom_of_the_well_compass", false, { {"images/dungeons/compass.png", "@disabled"}, {"images/dungeons/compass.png"} }, { {nil} })
ConditionalConsumable("Bottom of the Well Silver Rupees", "bottom_of_the_well_sr", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Bottom of the Well Small Keys", "bottom_of_the_well_small_keys", "images/dungeons/small_key.png")

ProgressiveVariableImage("Gerudo Training Ground Label", "gerudo_training_ground_label", true, { {"images/dungeons/labels/gerudo_training_ground.png"}, {"images/dungeons/labels/gerudo_training_ground.png", "overlay|images/overlays/va.png"}, {"images/dungeons/labels/gerudo_training_ground.png", "overlay|images/overlays/mq.png"} }, { {nil} })
ConditionalConsumable("Gerudo Training Ground Silver Rupees (Slopes)", "gerudo_training_ground_sr_slopes", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Gerudo Training Ground Silver Rupees (Lava)", "gerudo_training_ground_sr_lava", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Gerudo Training Ground Silver Rupees (Water)", "gerudo_training_ground_sr_water", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Gerudo Training Ground Small Keys", "gerudo_training_ground_small_keys", "images/dungeons/small_key.png")

ProgressiveVariableImage("Ganon's Castle Label", "ganons_castle_label", true, { {"images/dungeons/labels/ganons_castle.png"}, {"images/dungeons/labels/ganons_castle.png", "overlay|images/overlays/va.png"}, {"images/dungeons/labels/ganons_castle.png", "overlay|images/overlays/mq.png"} }, { {nil} })
ConditionalConsumable("Ganon's Castle Silver Rupees (Light)", "ganons_castle_sr_light", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Ganon's Castle Silver Rupees (Forest)", "ganons_castle_sr_forest", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Ganon's Castle Silver Rupees (Fire)", "ganons_castle_sr_fire", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Ganon's Castle Silver Rupees (Water)", "ganons_castle_sr_water", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Ganon's Castle Silver Rupees (Spirit)", "ganons_castle_sr_spirit", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Ganon's Castle Silver Rupees (Shadow)", "ganons_castle_sr_shadow", "images/dungeons/silver_rupee.png")
ConditionalConsumable("Ganon's Castle Small Keys", "ganons_castle_small_keys", "images/dungeons/small_key.png")
ConditionalToggle("Ganon's Castle Boss Key", "ganons_castle_boss_key", false, "images/dungeons/boss_key.png")

-- Ocarina Buttons
ConditionalToggle("A", "a", false, "images/ocarina_buttons/a.png")
ConditionalToggle("C-Up", "c-up", false, "images/ocarina_buttons/c-up.png")
ConditionalToggle("C-Right", "c-right", false, "images/ocarina_buttons/c-right.png")
ConditionalToggle("C-Down", "c-down", false, "images/ocarina_buttons/c-down.png")
ConditionalToggle("C-Left", "c-left", false, "images/ocarina_buttons/c-left.png")

-- Souls
if string.find(Tracker.ActiveVariantUID, "Souls") then
    ConditionalLabel("Boss Souls", "label_boss_souls", "images/souls/boss/label.png")
    ConditionalLabel("", "soul_filler_boss", "images/souls/filler.png")

    ConditionalOverlayToggle("Soul of Queen Gohma", "soul_queen_gohma", false, "images/souls/boss/queen_gohma.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of King Dodongo", "soul_king_dodongo", false, "images/souls/boss/king_dodongo.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Barinade", "soul_barinade", false, "images/souls/boss/barinade.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Odolwa", "soul_odolwa", false, "images/souls/boss/odolwa.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Goht", "soul_goht", false, "images/souls/boss/goht.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Gyorg", "soul_gyorg", false, "images/souls/boss/gyorg.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Twinmold", "soul_twinmold", false, "images/souls/boss/twinmold.png", "images/overlays/mm_padded.png")

    ConditionalOverlayToggle("Soul of Phantom Ganon", "soul_phantom_ganon", false, "images/souls/boss/phantom_ganon.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Volvagia", "soul_volvagia", false, "images/souls/boss/volvagia.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Morpha", "soul_morpha", false, "images/souls/boss/morpha.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Twinrova", "soul_twinrova", false, "images/souls/boss/twinrova.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Bongo Bongo", "soul_bongo_bongo", false, "images/souls/boss/bongo_bongo.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Igos", "soul_igos", false, "images/souls/boss/igos.png", "images/overlays/mm_padded.png")
    
    ConditionalLabel("Enemy Souls", "label_enemy_souls", "images/souls/enemy/label.png")

    ConditionalOverlayToggle("Soul of Anubis", "soul_anubis", false, "images/souls/enemy/anubis.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Armos", "soul_armos", false, "images/souls/enemy/armos.png", "")
    ConditionalOverlayToggle("Soul of Baby Dodongos", "soul_baby_dodongos", false, "images/souls/enemy/baby_dodongos.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Bad Bats", "soul_bad_bats", false, "images/souls/enemy/bad_bats.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Beamos", "soul_beamos", false, "images/souls/enemy/beamos.png", "")
    ConditionalOverlayToggle("Soul of Bio Babas", "soul_bio_babas", false, "images/souls/enemy/bio_babas.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Biris/Baris", "soul_biris_baris", false, "images/souls/enemy/biris_baris.png", "images/overlays/oot_padded.png")
    
    ConditionalOverlayToggle("Soul of Boes", "soul_boes", false, "images/souls/enemy/boes.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Bubbles", "soul_bubbles", false, "images/souls/enemy/bubbles.png", "")
    ConditionalOverlayToggle("Soul of Captain Keeta", "soul_captain_keeta", false, "images/souls/enemy/captain_keeta.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Chuchus", "soul_chuchus", false, "images/souls/enemy/chuchus.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Dark Link", "soul_dark_link", false, "images/souls/enemy/dark_link.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Dead Hands", "soul_dead_hands", false, "images/souls/enemy/dead_hands.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Deep Pythons", "soul_deep_pythons", false, "images/souls/enemy/deep_pythons.png", "images/overlays/mm_padded.png")
    
    ConditionalOverlayToggle("Soul of Deku Babas", "soul_deku_babas", false, "images/souls/enemy/deku_babas.png", "")
    ConditionalOverlayToggle("Soul of Deku Scrubs", "soul_deku_scrubs", false, "images/souls/enemy/deku_scrubs.png", "")
    ConditionalOverlayToggle("Soul of Dexihands", "soul_dexihands", false, "images/souls/enemy/dexihands.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Dodongos", "soul_dodongos", false, "images/souls/enemy/dodongos.png", "")
    ConditionalOverlayToggle("Soul of Dragonflies", "soul_dragonflies", false, "images/souls/enemy/dragonflies.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Eenoes", "soul_eenoes", false, "images/souls/enemy/eenoes.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Eyegores", "soul_eyegores", false, "images/souls/enemy/eyegores.png", "images/overlays/mm_padded.png")
    
    ConditionalOverlayToggle("Soul of Fighting Thieves", "soul_fighting_thieves", false, "images/souls/enemy/fighting_thieves.png", "")
    ConditionalOverlayToggle("Soul of Flare Dancers", "soul_flare_dancers", false, "images/souls/enemy/flare_dancers.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Floormasters", "soul_floormasters", false, "images/souls/enemy/floormasters.png", "")
    ConditionalOverlayToggle("Soul of Flying Pots", "soul_flying_pots", false, "images/souls/enemy/flying_pots.png", "")
    ConditionalOverlayToggle("Soul of Freezards", "soul_freezards", false, "images/souls/enemy/freezards.png", "")
    ConditionalOverlayToggle("Soul of Garo", "soul_garo", false, "images/souls/enemy/garo.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Gekkos", "soul_gekkos", false, "images/souls/enemy/gekkos.png", "images/overlays/mm_padded.png")
    
    ConditionalOverlayToggle("Soul of Gohma Larvaes", "soul_gohma_larvaes", false, "images/souls/enemy/gohma_larvaes.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Gomess", "soul_gomess", false, "images/souls/enemy/gomess.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Guays", "soul_guays", false, "images/souls/enemy/guays.png", "")
    ConditionalOverlayToggle("Soul of Hiploops", "soul_hiploops", false, "images/souls/enemy/hiploops.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Iron Knuckles", "soul_iron_knuckles", false, "images/souls/enemy/iron_knuckles.png", "")
    ConditionalOverlayToggle("Soul of Jabu-Jabu's Parasites", "soul_jabu_jabus_parasites", false, "images/souls/enemy/jabu_jabus_parasites.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Keese", "soul_keese", false, "images/souls/enemy/keese.png", "")
    
    ConditionalOverlayToggle("Soul of Leevers", "soul_leevers", false, "images/souls/enemy/leevers.png", "")
    ConditionalOverlayToggle("Soul of Like Likes", "soul_like_likes", false, "images/souls/enemy/like_likes.png", "")
    ConditionalOverlayToggle("Soul of Lizalfos/Dinolfos", "soul_lizalfos_dinolfos", false, "images/souls/enemy/lizalfos_dinolfos.png", "")
    ConditionalOverlayToggle("Soul of Moblins", "soul_moblins", false, "images/souls/enemy/moblins.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Nejirons", "soul_nejirons", false, "images/souls/enemy/nejirons.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Octoroks", "soul_octoroks", false, "images/souls/enemy/octoroks.png", "")
    ConditionalOverlayToggle("Soul of Peahats", "soul_peahats", false, "images/souls/enemy/peahats.png", "")
    
    ConditionalOverlayToggle("Soul of Real Bombchu", "soul_real_bombchu", false, "images/souls/enemy/real_bombchu.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of ReDeads/Gibdos", "soul_redeads_gibdos", false, "images/souls/enemy/redeads_gibdos.png", "")
    ConditionalOverlayToggle("Soul of Shaboms", "soul_shaboms", false, "images/souls/enemy/shaboms.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Shell Blades", "soul_shell_blades", false, "images/souls/enemy/shell_blades.png", "")
    ConditionalOverlayToggle("Soul of Skull Kids (OoT)", "soul_skull_kids_oot", false, "images/souls/enemy/skull_kids.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Skullfish (MM)", "soul_skullfish_mm", false, "images/souls/enemy/skullfish.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Skulltulas", "soul_skulltulas", false, "images/souls/enemy/skulltulas.png", "")
    
    ConditionalOverlayToggle("Soul of Skullwalltulas", "soul_skullwalltulas", false, "images/souls/enemy/skullwalltulas.png", "")
    ConditionalOverlayToggle("Soul of Snappers", "soul_snappers", false, "images/souls/enemy/snappers.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Spikes", "soul_spikes", false, "images/souls/enemy/spikes.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Stalchildren", "soul_stalchildren", false, "images/souls/enemy/stalchildren.png", "")
    ConditionalOverlayToggle("Soul of Stalfos (OoT)", "soul_stalfos_oot", false, "images/souls/enemy/stalfos.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Stingers", "soul_stingers", false, "images/souls/enemy/stingers.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Tailpasarans", "soul_tailpasarans", false, "images/souls/enemy/tailpasarans.png", "images/overlays/oot_padded.png")
    
    ConditionalOverlayToggle("Soul of Takkuri", "soul_takkuri", false, "images/souls/enemy/takkuri.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Tektites", "soul_tektites", false, "images/souls/enemy/tektites.png", "")
    ConditionalOverlayToggle("Soul of Torch Slugs", "soul_torch_slugs", false, "images/souls/enemy/torch_slugs.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Wallmasters", "soul_wallmasters", false, "images/souls/enemy/wallmasters.png", "")
    ConditionalOverlayToggle("Soul of Warts", "soul_warts", false, "images/souls/enemy/warts.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Wizzrobes", "soul_wizzrobes", false, "images/souls/enemy/wizzrobes.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Wolfos", "soul_wolfos", false, "images/souls/enemy/wolfos.png", "")
    
    ConditionalLabel("NPC Souls", "label_npc_souls", "images/souls/npc/label.png")

    ConditionalOverlayToggle("Soul of Biggoron", "soul_biggoron", false, "images/souls/npc/biggoron.png", "")
    ConditionalOverlayToggle("Soul of Blacksmiths", "soul_blacksmiths", false, "images/souls/npc/blacksmiths.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Bombchu Bowling/Chest Game Lady", "soul_bombchu_bowling_chest_game_lady", false, "images/souls/npc/bombchu_bowling_chest_game_lady.png", "")
    ConditionalOverlayToggle("Soul of Carpenters", "soul_carpenters", false, "images/souls/npc/carpenters.png", "")
    ConditionalOverlayToggle("Soul of Citizens", "soul_citizens", false, "images/souls/npc/citizens.png", "")
    ConditionalOverlayToggle("Soul of Composer Bros.", "soul_composer_bros", false, "images/souls/npc/composer_bros.png", "")
    ConditionalOverlayToggle("Soul of Cucco Lady/Anju", "soul_cucco_lady_anju", false, "images/souls/npc/cucco_lady_anju.png", "")

    ConditionalOverlayToggle("Soul of Dampe", "soul_dampe", false, "images/souls/npc/dampe.png", "")
    ConditionalOverlayToggle("Soul of Darunia", "soul_darunia", false, "images/souls/npc/darunia.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Fishing Pond/Trading Post Owner", "soul_fishing_pond_trading_post_owner", false, "images/souls/npc/fishing_pond_trading_post_owner.png", "")
    ConditionalOverlayToggle("Soul of Gorons", "soul_gorons", false, "images/souls/npc/gorons.png", "")
    ConditionalOverlayToggle("Soul of Guru-Guru", "soul_guru_guru", false, "images/souls/npc/guru_guru.png", "")
    ConditionalOverlayToggle("Soul of Honey & Darling", "soul_honey_darling", false, "images/souls/npc/honey_darling.png", "")
    ConditionalOverlayToggle("Soul of Hylian Guard", "soul_hylian_guard", false, "images/souls/npc/hylian_guard.png", "images/overlays/oot_padded.png")

    ConditionalOverlayToggle("Soul of Ingo/Gorman & Bros.", "soul_ingo_gorman_bros", false, "images/souls/npc/ingo_gorman_bros.png", "")
    ConditionalOverlayToggle("Soul of Kafei", "soul_kafei", false, "images/souls/npc/kafei.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Keaton", "soul_keaton", false, "images/souls/npc/keaton.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of King Zora", "soul_king_zora", false, "images/souls/npc/king_zora.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Kokiri", "soul_kokiri", false, "images/souls/npc/kokiri.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Kokiri Shopkeeper", "soul_kokiri_shopkeeper", false, "images/souls/npc/kokiri_shopkeeper.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Koume and Kotake", "soul_koume_and_kotake", false, "images/souls/npc/koume_and_kotake.png", "images/overlays/mm_padded.png")

    ConditionalOverlayToggle("Soul of Madame Aroma (MM)", "soul_madame_aroma_mm", false, "images/souls/npc/madame_aroma.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Malon/Romani/Cremia", "soul_malon_romani_cremia", false, "images/souls/npc/malon_romani_cremia.png", "")
    ConditionalOverlayToggle("Soul of Mayor Dotour", "soul_mayor_dotour", false, "images/souls/npc/mayor_dotour.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Medigoron/Keg Trial Goron", "soul_medigoron_keg_trial_goron", false, "images/souls/npc/medigoron_keg_trial_goron.png", "")
    ConditionalOverlayToggle("Soul of Mido", "soul_mido", false, "images/souls/npc/mido.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Moon Children", "soul_moon_children", false, "images/souls/npc/moon_children.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Playground Scrubs", "soul_playground_scrubs", false, "images/souls/npc/playground_scrubs.png", "images/overlays/mm_padded.png")

    ConditionalOverlayToggle("Soul of Poe Collector/Ghost Hut Owner", "soul_poe_collector_ghost_hut_owner", false, "images/souls/npc/poe_collector_ghost_hut_owner.png", "")
    ConditionalOverlayToggle("Soul of Potion Shopkeeper", "soul_potion_shopkeeper", false, "images/souls/npc/potion_shopkeeper.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Rooftop Man/Part-Timer", "soul_rooftop_man_part_timer", false, "images/souls/npc/rooftop_man_part_timer.png", "")
    ConditionalOverlayToggle("Soul of Ruto/Lulu", "soul_ruto_lulu", false, "images/souls/npc/ruto_lulu.png", "")
    ConditionalOverlayToggle("Soul of Saria", "soul_saria", false, "images/souls/npc/saria.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Sheik", "soul_sheik", false, "images/souls/npc/sheik.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Talon/Mr. Barten", "soul_talon_mr_barten", false, "images/souls/npc/talon_mr_barten.png", "")

    ConditionalOverlayToggle("Soul of the Astronomer", "soul_astronomer", false, "images/souls/npc/astronomer.png", "")
    ConditionalOverlayToggle("Soul of the Bazaar/Swamp Archery Owner", "soul_bazaar_swamp_archery_owner", false, "images/souls/npc/bazaar_swamp_archery_owner.png", "")
    ConditionalOverlayToggle("Soul of the Bean Salesman", "soul_bean_salesman", false, "images/souls/npc/bean_salesman.png", "")
    ConditionalOverlayToggle("Soul of the Beggar/Banker", "soul_beggar_banker", false, "images/souls/npc/beggar_banker.png", "")
    ConditionalOverlayToggle("Soul of the Bombchu/Bomb Shop Owner", "soul_bombchu_bomb_shop_owner", false, "images/souls/npc/bombchu_bomb_shop_owner.png", "")
    ConditionalOverlayToggle("Soul of the Carpet Man/Swordsman", "soul_carpet_man_swordsman", false, "images/souls/npc/carpet_man_swordsman.png", "")
    ConditionalOverlayToggle("Soul of the Chest Game Owner/Fisherman", "soul_chest_game_owner_fisherman", false, "images/souls/npc/chest_game_owner_fisherman.png", "")

    ConditionalOverlayToggle("Soul of the Deku Butler", "soul_deku_butler", false, "images/souls/npc/deku_butler.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of the Deku King", "soul_deku_king", false, "images/souls/npc/deku_king.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of the Deku Princess", "soul_deku_princess", false, "images/souls/npc/deku_princess.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of the Dog Lady", "soul_dog_lady", false, "images/souls/npc/dog_lady.png", "")
    ConditionalOverlayToggle("Soul of the Goron Child/Baby", "soul_goron_child_baby", false, "images/souls/npc/goron_child_baby.png", "")
    ConditionalOverlayToggle("Soul of the Goron Elder", "soul_goron_elder", false, "images/souls/npc/goron_elder.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of the Goron Shopkeeper", "soul_goron_shopkeeper", false, "images/souls/npc/goron_shopkeeper.png", "")

    ConditionalOverlayToggle("Soul of the Graveyard Kid/Bombers", "soul_graveyard_kid_bombers", false, "images/souls/npc/graveyard_kid_bombers.png", "")
    ConditionalOverlayToggle("Soul of the Old Hag/Anju's Grandmother", "soul_old_hag_anjus_grandmother", false, "images/souls/npc/old_hag_anjus_grandmother.png", "")
    ConditionalOverlayToggle("Soul of the Patrolling Thieves and their Chief", "soul_patrolling_thieves_and_their_chief", false, "images/souls/npc/patrolling_thieves_and_their_chief.png", "")
    ConditionalOverlayToggle("Soul of the Punk Kid/Grog", "soul_punk_kid_grog", false, "images/souls/npc/punk_kid_grog.png", "")
    ConditionalOverlayToggle("Soul of the Scientist", "soul_scientist", false, "images/souls/npc/scientist.png", "")
    ConditionalOverlayToggle("Soul of the Shooting Gallery/Town Archery Owner", "soul_shooting_gallery_town_archery_owner", false, "images/souls/npc/shooting_gallery_town_archery_owner.png", "")
    ConditionalOverlayToggle("Soul of the Zora Musicians", "soul_zora_musicians", false, "images/souls/npc/zora_musicians.png", "images/overlays/mm_padded.png")

    ConditionalOverlayToggle("Soul of the Zora Shopkeeper", "soul_zora_shopkeeper", false, "images/souls/npc/zora_shopkeeper.png", "")
    ConditionalOverlayToggle("Soul of Tingle", "soul_tingle", false, "images/souls/npc/tingle.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Toilet Hand", "soul_toilet_hand", false, "images/souls/npc/toilet_hand.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Toto (MM)", "soul_toto_mm", false, "images/souls/npc/toto.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Tourist Center Owner", "soul_tourist_center_owner", false, "images/souls/npc/tourist_center_owner.png", "images/overlays/mm_padded.png")
    ConditionalOverlayToggle("Soul of Zelda", "soul_zelda", false, "images/souls/npc/zelda.png", "images/overlays/oot_padded.png")
    ConditionalOverlayToggle("Soul of Zoras", "soul_zoras", false, "images/souls/npc/zoras.png", "")
    
    ConditionalLabel("Misc. Souls", "label_misc_souls", "images/souls/misc/label.png")

    ConditionalOverlayToggle("Soul of Business Scrubs", "soul_business_scrubs", false, "images/souls/misc/business_scrubs.png", "")
    ConditionalOverlayToggle("Soul of Gold Skulltulas", "soul_gold_skulltulas", false, "images/souls/misc/gold_skulltulas.png", "")
end